// Interface automatically generated by schemas-to-ts

import { Organization } from '../../../organization/content-types/organization/organization';
import { Country } from '../../../country/content-types/country/country';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { Address } from '../../../address/content-types/address/address';
import { User } from '../../../../common/schemas-to-ts/User';
import { Organization_Plain } from '../../../organization/content-types/organization/organization';
import { Country_Plain } from '../../../country/content-types/country/country';
import { Address_Plain } from '../../../address/content-types/address/address';
import { User_Plain } from '../../../../common/schemas-to-ts/User';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Branch {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    full_name?: string;
    code?: string;
    organization?: { data: Organization };
    active?: boolean;
    is_default?: boolean;
    country?: { data: Country };
    logo?: { data: Media };
    address?: { data: Address };
    owner?: { data: User };
    locale: string;
    localizations?: { data: Branch[] };
  };
}
export interface Branch_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  full_name?: string;
  code?: string;
  organization?: Organization_Plain;
  active?: boolean;
  is_default?: boolean;
  country?: Country_Plain;
  logo?: Media;
  address?: Address_Plain;
  owner?: User_Plain;
  locale: string;
  localizations?: Branch[];
}

export interface Branch_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  full_name?: string;
  code?: string;
  organization?: number;
  active?: boolean;
  is_default?: boolean;
  country?: number;
  logo?: number;
  address?: number;
  owner?: number;
  locale: string;
  localizations?: Branch[];
}

export interface Branch_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  full_name?: string;
  code?: string;
  organization?: AdminPanelRelationPropertyModification<Organization_Plain>;
  active?: boolean;
  is_default?: boolean;
  country?: AdminPanelRelationPropertyModification<Country_Plain>;
  logo?: AdminPanelRelationPropertyModification<Media>;
  address?: AdminPanelRelationPropertyModification<Address_Plain>;
  owner?: AdminPanelRelationPropertyModification<User_Plain>;
  locale: string;
  localizations?: Branch[];
}
