// Interface automatically generated by schemas-to-ts

export interface ContactPerson {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    contact_id: string;
    contact_person_id: string;
    salutation?: string;
    first_name?: string;
    last_name?: string;
    email?: string;
    phone?: string;
    mobile?: string;
    is_primary_contact?: boolean;
    skype?: string;
    designation?: string;
    department?: string;
    is_added_in_portal?: boolean;
    locale: string;
    localizations?: { data: ContactPerson[] };
  };
}
export interface ContactPerson_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  contact_id: string;
  contact_person_id: string;
  salutation?: string;
  first_name?: string;
  last_name?: string;
  email?: string;
  phone?: string;
  mobile?: string;
  is_primary_contact?: boolean;
  skype?: string;
  designation?: string;
  department?: string;
  is_added_in_portal?: boolean;
  locale: string;
  localizations?: ContactPerson[];
}

export interface ContactPerson_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  contact_id: string;
  contact_person_id: string;
  salutation?: string;
  first_name?: string;
  last_name?: string;
  email?: string;
  phone?: string;
  mobile?: string;
  is_primary_contact?: boolean;
  skype?: string;
  designation?: string;
  department?: string;
  is_added_in_portal?: boolean;
  locale: string;
  localizations?: ContactPerson[];
}

export interface ContactPerson_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  contact_id: string;
  contact_person_id: string;
  salutation?: string;
  first_name?: string;
  last_name?: string;
  email?: string;
  phone?: string;
  mobile?: string;
  is_primary_contact?: boolean;
  skype?: string;
  designation?: string;
  department?: string;
  is_added_in_portal?: boolean;
  locale: string;
  localizations?: ContactPerson[];
}
