// Interface automatically generated by schemas-to-ts

export interface Organization {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    organization_id: string;
    name: string;
    is_logo_uploaded?: string;
    is_default_org: boolean;
    user_role?: string;
    account_created_date: Date;
    time_zone: string;
    language_code: string;
    date_format: string;
    field_separator: string;
    fiscal_year_start_month: number;
    tax_group_enabled: boolean;
    user_status?: string;
    contact_name: string;
    industry_type: string;
    locale: string;
    localizations?: { data: Organization[] };
  };
}
export interface Organization_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  organization_id: string;
  name: string;
  is_logo_uploaded?: string;
  is_default_org: boolean;
  user_role?: string;
  account_created_date: Date;
  time_zone: string;
  language_code: string;
  date_format: string;
  field_separator: string;
  fiscal_year_start_month: number;
  tax_group_enabled: boolean;
  user_status?: string;
  contact_name: string;
  industry_type: string;
  locale: string;
  localizations?: Organization[];
}

export interface Organization_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  organization_id: string;
  name: string;
  is_logo_uploaded?: string;
  is_default_org: boolean;
  user_role?: string;
  account_created_date: Date;
  time_zone: string;
  language_code: string;
  date_format: string;
  field_separator: string;
  fiscal_year_start_month: number;
  tax_group_enabled: boolean;
  user_status?: string;
  contact_name: string;
  industry_type: string;
  locale: string;
  localizations?: Organization[];
}

export interface Organization_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  organization_id: string;
  name: string;
  is_logo_uploaded?: string;
  is_default_org: boolean;
  user_role?: string;
  account_created_date: Date;
  time_zone: string;
  language_code: string;
  date_format: string;
  field_separator: string;
  fiscal_year_start_month: number;
  tax_group_enabled: boolean;
  user_status?: string;
  contact_name: string;
  industry_type: string;
  locale: string;
  localizations?: Organization[];
}
