// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Store } from '../../../store/content-types/store/store';
import { Store_Plain } from '../../../store/content-types/store/store';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Type {
  Gateway = 'gateway',
  Cash = 'cash',
  Credit = 'credit',
  Other = 'other',}

export interface PaymentMethod {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    active?: boolean;
    default?: boolean;
    description?: string;
    help?: string;
    logo?: { data: Media };
    meta?: any;
    store?: { data: Store };
    type?: Type;
  };
}
export interface PaymentMethod_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  active?: boolean;
  default?: boolean;
  description?: string;
  help?: string;
  logo?: Media;
  meta?: any;
  store?: Store_Plain;
  type?: Type;
}

export interface PaymentMethod_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  active?: boolean;
  default?: boolean;
  description?: string;
  help?: string;
  logo?: number;
  meta?: any;
  store?: number;
  type?: Type;
}

export interface PaymentMethod_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  active?: boolean;
  default?: boolean;
  description?: string;
  help?: string;
  logo?: AdminPanelRelationPropertyModification<Media>;
  meta?: any;
  store?: AdminPanelRelationPropertyModification<Store_Plain>;
  type?: Type;
}
