// Interface automatically generated by schemas-to-ts

export interface ZohoAuth {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    code?: string;
    error?: string;
    expires_in?: number;
    refresh_token?: string;
    access_token?: string;
  };
}
export interface ZohoAuth_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  code?: string;
  error?: string;
  expires_in?: number;
  refresh_token?: string;
  access_token?: string;
}

export interface ZohoAuth_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  code?: string;
  error?: string;
  expires_in?: number;
  refresh_token?: string;
  access_token?: string;
}

export interface ZohoAuth_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  code?: string;
  error?: string;
  expires_in?: number;
  refresh_token?: string;
  access_token?: string;
}
