// Interface automatically generated by schemas-to-ts

export interface Payment {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    payment_id: string;
    payment_mode: string;
    amount: number;
    amount_refunded: number;
    bank_charges: number;
    date: Date;
    status: string;
    reference_number: string;
    description?: string;
    customer_id: string;
    customer_name: string;
    email?: string;
    tax_amount_withheld?: number;
    exchange_rate?: number;
    currency_id: string;
    currency_code: string;
    currency_symbol: string;
    account_id: string;
    account_name: string;
    tax_account_id?: string;
    tax_account_name?: string;
    unused_amount?: number;
    last_four_digits?: number;
    custom_fields?: any;
    locale: string;
    localizations?: { data: Payment[] };
  };
}
export interface Payment_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  payment_id: string;
  payment_mode: string;
  amount: number;
  amount_refunded: number;
  bank_charges: number;
  date: Date;
  status: string;
  reference_number: string;
  description?: string;
  customer_id: string;
  customer_name: string;
  email?: string;
  tax_amount_withheld?: number;
  exchange_rate?: number;
  currency_id: string;
  currency_code: string;
  currency_symbol: string;
  account_id: string;
  account_name: string;
  tax_account_id?: string;
  tax_account_name?: string;
  unused_amount?: number;
  last_four_digits?: number;
  custom_fields?: any;
  locale: string;
  localizations?: Payment[];
}

export interface Payment_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  payment_id: string;
  payment_mode: string;
  amount: number;
  amount_refunded: number;
  bank_charges: number;
  date: Date;
  status: string;
  reference_number: string;
  description?: string;
  customer_id: string;
  customer_name: string;
  email?: string;
  tax_amount_withheld?: number;
  exchange_rate?: number;
  currency_id: string;
  currency_code: string;
  currency_symbol: string;
  account_id: string;
  account_name: string;
  tax_account_id?: string;
  tax_account_name?: string;
  unused_amount?: number;
  last_four_digits?: number;
  custom_fields?: any;
  locale: string;
  localizations?: Payment[];
}

export interface Payment_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  payment_id: string;
  payment_mode: string;
  amount: number;
  amount_refunded: number;
  bank_charges: number;
  date: Date;
  status: string;
  reference_number: string;
  description?: string;
  customer_id: string;
  customer_name: string;
  email?: string;
  tax_amount_withheld?: number;
  exchange_rate?: number;
  currency_id: string;
  currency_code: string;
  currency_symbol: string;
  account_id: string;
  account_name: string;
  tax_account_id?: string;
  tax_account_name?: string;
  unused_amount?: number;
  last_four_digits?: number;
  custom_fields?: any;
  locale: string;
  localizations?: Payment[];
}
