// Interface automatically generated by schemas-to-ts

import { AttributeFamily } from '../../../attribute-family/content-types/attribute-family/attribute-family';
import { Store } from '../../../store/content-types/store/store';
import { AttributeFamily_Plain } from '../../../attribute-family/content-types/attribute-family/attribute-family';
import { Store_Plain } from '../../../store/content-types/store/store';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Product {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    type: string;
    parents: { data: Product[] };
    sku?: string;
    active?: boolean;
    attribute_family?: { data: AttributeFamily };
    stores: { data: Store[] };
    locale: string;
    localizations?: { data: Product[] };
  };
}
export interface Product_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  type: string;
  parents: Product_Plain[];
  sku?: string;
  active?: boolean;
  attribute_family?: AttributeFamily_Plain;
  stores: Store_Plain[];
  locale: string;
  localizations?: Product[];
}

export interface Product_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  type: string;
  parents: number[];
  sku?: string;
  active?: boolean;
  attribute_family?: number;
  stores: number[];
  locale: string;
  localizations?: Product[];
}

export interface Product_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  type: string;
  parents: AdminPanelRelationPropertyModification<Product_Plain>;
  sku?: string;
  active?: boolean;
  attribute_family?: AdminPanelRelationPropertyModification<AttributeFamily_Plain>;
  stores: AdminPanelRelationPropertyModification<Store_Plain>;
  locale: string;
  localizations?: Product[];
}
