// Interface automatically generated by schemas-to-ts

import { ContactPerson } from '../../../contact-person/content-types/contact-person/contact-person';
import { ContactPerson_Plain } from '../../../contact-person/content-types/contact-person/contact-person';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Status {
  Fulfilled = 'fulfilled',
  Processing = 'processing',
  Cancelled = 'cancelled',}
export enum DiscountType {
  EntityLevel = 'entity_level',
  ItemLevel = 'item_level',}

export interface Order {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    salesorder_id?: number;
    salesorder_number?: string;
    date?: Date;
    status?: Status;
    shipment_date?: Date;
    reference_number?: string;
    customer_id?: number;
    customer_name?: string;
    contact_persons?: any;
    currency_id?: number;
    currency_code?: string;
    currency_symbol?: string;
    exchange_rate?: number;
    discount_amount?: number;
    discount?: string;
    is_discount_before_tax?: boolean;
    discount_type?: DiscountType;
    estimate_id?: number;
    delivery_method?: string;
    delivery_method_id?: number;
    line_items?: any;
    shipping_charge?: number;
    adjustment?: number;
    adjustment_description?: string;
    sub_total?: number;
    tax_total?: number;
    total?: number;
    taxes?: any;
    price_precision?: number;
    pricebook_id?: number;
    shipping_address?: any;
    billing_address?: any;
    notes?: string;
    terms?: string;
    template_id?: number;
    template_name?: string;
    template_type?: string;
    created_time?: Date;
    last_modified_time?: Date;
    salesperson_id?: number;
    salesperson_name?: string;
    documents?: any;
    is_pre_gst?: boolean;
    gst_no?: string;
    gst_treatment?: string;
    place_of_supply?: string;
    contacts: { data: ContactPerson[] };
    locale: string;
    localizations?: { data: Order[] };
  };
}
export interface Order_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  salesorder_id?: number;
  salesorder_number?: string;
  date?: Date;
  status?: Status;
  shipment_date?: Date;
  reference_number?: string;
  customer_id?: number;
  customer_name?: string;
  contact_persons?: any;
  currency_id?: number;
  currency_code?: string;
  currency_symbol?: string;
  exchange_rate?: number;
  discount_amount?: number;
  discount?: string;
  is_discount_before_tax?: boolean;
  discount_type?: DiscountType;
  estimate_id?: number;
  delivery_method?: string;
  delivery_method_id?: number;
  line_items?: any;
  shipping_charge?: number;
  adjustment?: number;
  adjustment_description?: string;
  sub_total?: number;
  tax_total?: number;
  total?: number;
  taxes?: any;
  price_precision?: number;
  pricebook_id?: number;
  shipping_address?: any;
  billing_address?: any;
  notes?: string;
  terms?: string;
  template_id?: number;
  template_name?: string;
  template_type?: string;
  created_time?: Date;
  last_modified_time?: Date;
  salesperson_id?: number;
  salesperson_name?: string;
  documents?: any;
  is_pre_gst?: boolean;
  gst_no?: string;
  gst_treatment?: string;
  place_of_supply?: string;
  contacts: ContactPerson_Plain[];
  locale: string;
  localizations?: Order[];
}

export interface Order_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  salesorder_id?: number;
  salesorder_number?: string;
  date?: Date;
  status?: Status;
  shipment_date?: Date;
  reference_number?: string;
  customer_id?: number;
  customer_name?: string;
  contact_persons?: any;
  currency_id?: number;
  currency_code?: string;
  currency_symbol?: string;
  exchange_rate?: number;
  discount_amount?: number;
  discount?: string;
  is_discount_before_tax?: boolean;
  discount_type?: DiscountType;
  estimate_id?: number;
  delivery_method?: string;
  delivery_method_id?: number;
  line_items?: any;
  shipping_charge?: number;
  adjustment?: number;
  adjustment_description?: string;
  sub_total?: number;
  tax_total?: number;
  total?: number;
  taxes?: any;
  price_precision?: number;
  pricebook_id?: number;
  shipping_address?: any;
  billing_address?: any;
  notes?: string;
  terms?: string;
  template_id?: number;
  template_name?: string;
  template_type?: string;
  created_time?: Date;
  last_modified_time?: Date;
  salesperson_id?: number;
  salesperson_name?: string;
  documents?: any;
  is_pre_gst?: boolean;
  gst_no?: string;
  gst_treatment?: string;
  place_of_supply?: string;
  contacts: number[];
  locale: string;
  localizations?: Order[];
}

export interface Order_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  salesorder_id?: number;
  salesorder_number?: string;
  date?: Date;
  status?: Status;
  shipment_date?: Date;
  reference_number?: string;
  customer_id?: number;
  customer_name?: string;
  contact_persons?: any;
  currency_id?: number;
  currency_code?: string;
  currency_symbol?: string;
  exchange_rate?: number;
  discount_amount?: number;
  discount?: string;
  is_discount_before_tax?: boolean;
  discount_type?: DiscountType;
  estimate_id?: number;
  delivery_method?: string;
  delivery_method_id?: number;
  line_items?: any;
  shipping_charge?: number;
  adjustment?: number;
  adjustment_description?: string;
  sub_total?: number;
  tax_total?: number;
  total?: number;
  taxes?: any;
  price_precision?: number;
  pricebook_id?: number;
  shipping_address?: any;
  billing_address?: any;
  notes?: string;
  terms?: string;
  template_id?: number;
  template_name?: string;
  template_type?: string;
  created_time?: Date;
  last_modified_time?: Date;
  salesperson_id?: number;
  salesperson_name?: string;
  documents?: any;
  is_pre_gst?: boolean;
  gst_no?: string;
  gst_treatment?: string;
  place_of_supply?: string;
  contacts: AdminPanelRelationPropertyModification<ContactPerson_Plain>[];
  locale: string;
  localizations?: Order[];
}
