// Interface automatically generated by schemas-to-ts

export enum ContactType {
  Customer = 'customer',
  Vendor = 'vendor',}
export enum LanguageCode {
  De = 'de',
  En = 'en',
  Es = 'es',
  Fr = 'fr',
  It = 'it',
  Ja = 'ja',
  Nl = 'nl',
  Pt = 'pt',
  Sv = 'sv',
  Zh = 'zh',}

export interface Contact {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    contact_id: string;
    contact_name: string;
    company_name?: string;
    has_transaction?: boolean;
    contact_type?: ContactType;
    is_linked_with_zohocrm?: boolean;
    website?: string;
    primary_contact_id?: string;
    payment_terms?: number;
    payment_terms_label?: string;
    currency_id?: string;
    currency_code?: string;
    currency_symbol?: string;
    language_code?: LanguageCode;
    outstanding_receivable_amount?: number;
    outstanding_receivable_amount_bcy?: number;
    unused_credits_receivable_amount?: number;
    unused_credits_receivable_amount_bcy?: number;
    status?: string;
    payment_reminder_enabled?: boolean;
    notes?: string;
    created_time?: Date;
    last_modified_time?: Date;
    is_taxable?: boolean;
    tax_id?: string;
    tax_name?: string;
    tax_percentage?: number;
    tax_authority_id?: string;
    tax_exemption_id?: string;
    tax_authority_name?: string;
    tax_exemption_code?: string;
    place_of_contact?: string;
    gst_no?: string;
    vat_treatment?: string;
    tax_treatment?: string;
    tax_regime?: string;
    is_tds_registered?: boolean;
    gst_treatment?: string;
    locale: string;
    localizations?: { data: Contact[] };
  };
}
export interface Contact_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  contact_id: string;
  contact_name: string;
  company_name?: string;
  has_transaction?: boolean;
  contact_type?: ContactType;
  is_linked_with_zohocrm?: boolean;
  website?: string;
  primary_contact_id?: string;
  payment_terms?: number;
  payment_terms_label?: string;
  currency_id?: string;
  currency_code?: string;
  currency_symbol?: string;
  language_code?: LanguageCode;
  outstanding_receivable_amount?: number;
  outstanding_receivable_amount_bcy?: number;
  unused_credits_receivable_amount?: number;
  unused_credits_receivable_amount_bcy?: number;
  status?: string;
  payment_reminder_enabled?: boolean;
  notes?: string;
  created_time?: Date;
  last_modified_time?: Date;
  is_taxable?: boolean;
  tax_id?: string;
  tax_name?: string;
  tax_percentage?: number;
  tax_authority_id?: string;
  tax_exemption_id?: string;
  tax_authority_name?: string;
  tax_exemption_code?: string;
  place_of_contact?: string;
  gst_no?: string;
  vat_treatment?: string;
  tax_treatment?: string;
  tax_regime?: string;
  is_tds_registered?: boolean;
  gst_treatment?: string;
  locale: string;
  localizations?: Contact[];
}

export interface Contact_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  contact_id: string;
  contact_name: string;
  company_name?: string;
  has_transaction?: boolean;
  contact_type?: ContactType;
  is_linked_with_zohocrm?: boolean;
  website?: string;
  primary_contact_id?: string;
  payment_terms?: number;
  payment_terms_label?: string;
  currency_id?: string;
  currency_code?: string;
  currency_symbol?: string;
  language_code?: LanguageCode;
  outstanding_receivable_amount?: number;
  outstanding_receivable_amount_bcy?: number;
  unused_credits_receivable_amount?: number;
  unused_credits_receivable_amount_bcy?: number;
  status?: string;
  payment_reminder_enabled?: boolean;
  notes?: string;
  created_time?: Date;
  last_modified_time?: Date;
  is_taxable?: boolean;
  tax_id?: string;
  tax_name?: string;
  tax_percentage?: number;
  tax_authority_id?: string;
  tax_exemption_id?: string;
  tax_authority_name?: string;
  tax_exemption_code?: string;
  place_of_contact?: string;
  gst_no?: string;
  vat_treatment?: string;
  tax_treatment?: string;
  tax_regime?: string;
  is_tds_registered?: boolean;
  gst_treatment?: string;
  locale: string;
  localizations?: Contact[];
}

export interface Contact_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  contact_id: string;
  contact_name: string;
  company_name?: string;
  has_transaction?: boolean;
  contact_type?: ContactType;
  is_linked_with_zohocrm?: boolean;
  website?: string;
  primary_contact_id?: string;
  payment_terms?: number;
  payment_terms_label?: string;
  currency_id?: string;
  currency_code?: string;
  currency_symbol?: string;
  language_code?: LanguageCode;
  outstanding_receivable_amount?: number;
  outstanding_receivable_amount_bcy?: number;
  unused_credits_receivable_amount?: number;
  unused_credits_receivable_amount_bcy?: number;
  status?: string;
  payment_reminder_enabled?: boolean;
  notes?: string;
  created_time?: Date;
  last_modified_time?: Date;
  is_taxable?: boolean;
  tax_id?: string;
  tax_name?: string;
  tax_percentage?: number;
  tax_authority_id?: string;
  tax_exemption_id?: string;
  tax_authority_name?: string;
  tax_exemption_code?: string;
  place_of_contact?: string;
  gst_no?: string;
  vat_treatment?: string;
  tax_treatment?: string;
  tax_regime?: string;
  is_tds_registered?: boolean;
  gst_treatment?: string;
  locale: string;
  localizations?: Contact[];
}
