// Interface automatically generated by schemas-to-ts

export enum DiscountType {
  Flat = 'flat',
  Percentage = 'percentage',}

export interface Coupon {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    is_enabled: boolean;
    coupon_code: string;
    discount: string;
    discount_type: DiscountType;
    locale: string;
    localizations?: { data: Coupon[] };
  };
}
export interface Coupon_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  is_enabled: boolean;
  coupon_code: string;
  discount: string;
  discount_type: DiscountType;
  locale: string;
  localizations?: Coupon[];
}

export interface Coupon_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  is_enabled: boolean;
  coupon_code: string;
  discount: string;
  discount_type: DiscountType;
  locale: string;
  localizations?: Coupon[];
}

export interface Coupon_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  is_enabled: boolean;
  coupon_code: string;
  discount: string;
  discount_type: DiscountType;
  locale: string;
  localizations?: Coupon[];
}
