// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Country {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    code?: string;
    icon?: string;
    image?: { data: Media };
    locale: string;
    localizations?: { data: Country[] };
  };
}
export interface Country_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  code?: string;
  icon?: string;
  image?: Media;
  locale: string;
  localizations?: Country[];
}

export interface Country_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  code?: string;
  icon?: string;
  image?: number;
  locale: string;
  localizations?: Country[];
}

export interface Country_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  code?: string;
  icon?: string;
  image?: AdminPanelRelationPropertyModification<Media>;
  locale: string;
  localizations?: Country[];
}
