// Interface automatically generated by schemas-to-ts

export interface Lineitem {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    item_id: number;
    line_item_id: number;
    name: string;
    description?: string;
    item_order?: number;
    bcy_rate: number;
    rate: number;
    quantity: number;
    quantity_invoiced: number;
    quantity_packed: number;
    quantity_shipped: number;
    unit: string;
    tax_id: number;
    tds_tax_id?: string;
    tax_name: string;
    tax_type: string;
    tax_percentage: number;
    item_total: number;
    is_invoiced: boolean;
    image_id?: number;
    image_name?: string;
    image_type?: string;
    warehouse_id: number;
    hsn_or_sac: number;
    sat_item_key_code: number;
    unitkey_code: string;
    locale: string;
    localizations?: { data: Lineitem[] };
  };
}
export interface Lineitem_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  item_id: number;
  line_item_id: number;
  name: string;
  description?: string;
  item_order?: number;
  bcy_rate: number;
  rate: number;
  quantity: number;
  quantity_invoiced: number;
  quantity_packed: number;
  quantity_shipped: number;
  unit: string;
  tax_id: number;
  tds_tax_id?: string;
  tax_name: string;
  tax_type: string;
  tax_percentage: number;
  item_total: number;
  is_invoiced: boolean;
  image_id?: number;
  image_name?: string;
  image_type?: string;
  warehouse_id: number;
  hsn_or_sac: number;
  sat_item_key_code: number;
  unitkey_code: string;
  locale: string;
  localizations?: Lineitem[];
}

export interface Lineitem_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  item_id: number;
  line_item_id: number;
  name: string;
  description?: string;
  item_order?: number;
  bcy_rate: number;
  rate: number;
  quantity: number;
  quantity_invoiced: number;
  quantity_packed: number;
  quantity_shipped: number;
  unit: string;
  tax_id: number;
  tds_tax_id?: string;
  tax_name: string;
  tax_type: string;
  tax_percentage: number;
  item_total: number;
  is_invoiced: boolean;
  image_id?: number;
  image_name?: string;
  image_type?: string;
  warehouse_id: number;
  hsn_or_sac: number;
  sat_item_key_code: number;
  unitkey_code: string;
  locale: string;
  localizations?: Lineitem[];
}

export interface Lineitem_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  item_id: number;
  line_item_id: number;
  name: string;
  description?: string;
  item_order?: number;
  bcy_rate: number;
  rate: number;
  quantity: number;
  quantity_invoiced: number;
  quantity_packed: number;
  quantity_shipped: number;
  unit: string;
  tax_id: number;
  tds_tax_id?: string;
  tax_name: string;
  tax_type: string;
  tax_percentage: number;
  item_total: number;
  is_invoiced: boolean;
  image_id?: number;
  image_name?: string;
  image_type?: string;
  warehouse_id: number;
  hsn_or_sac: number;
  sat_item_key_code: number;
  unitkey_code: string;
  locale: string;
  localizations?: Lineitem[];
}
