// Interface automatically generated by schemas-to-ts

export interface Warehouse {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    warehouse_name: string;
    address: string;
    city: string;
    state: string;
    country: string;
    zip: number;
    phone: string;
    email: string;
    locale: string;
    localizations?: { data: Warehouse[] };
  };
}
export interface Warehouse_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  warehouse_name: string;
  address: string;
  city: string;
  state: string;
  country: string;
  zip: number;
  phone: string;
  email: string;
  locale: string;
  localizations?: Warehouse[];
}

export interface Warehouse_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  warehouse_name: string;
  address: string;
  city: string;
  state: string;
  country: string;
  zip: number;
  phone: string;
  email: string;
  locale: string;
  localizations?: Warehouse[];
}

export interface Warehouse_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  warehouse_name: string;
  address: string;
  city: string;
  state: string;
  country: string;
  zip: number;
  phone: string;
  email: string;
  locale: string;
  localizations?: Warehouse[];
}
