// Interface automatically generated by schemas-to-ts

import { User } from '../../../../common/schemas-to-ts/User';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { Branch } from '../../../branch/content-types/branch/branch';
import { Currency } from '../../../currency/content-types/currency/currency';
import { Warehouse } from '../../../warehouse/content-types/warehouse/warehouse';
import { Vendor } from '../../../vendor/content-types/vendor/vendor';
import { User_Plain } from '../../../../common/schemas-to-ts/User';
import { Branch_Plain } from '../../../branch/content-types/branch/branch';
import { Currency_Plain } from '../../../currency/content-types/currency/currency';
import { Warehouse_Plain } from '../../../warehouse/content-types/warehouse/warehouse';
import { Vendor_Plain } from '../../../vendor/content-types/vendor/vendor';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Stage {
  Development = 'Development',
  Test = 'Test',
  Production = 'Production',}

export interface Organization {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    organization_id: string;
    title: string;
    is_default_org: boolean;
    user_role?: string;
    time_zone: string;
    language_code: string;
    date_format: string;
    field_separator: string;
    fiscal_year_start_month: number;
    tax_group_enabled: boolean;
    industry_type: string;
    stage: Stage;
    full_name?: string;
    owner?: { data: User };
    images?: { data: Media[] };
    logo?: { data: Media };
    members?: { data: User[] };
    active?: boolean;
    has_branch?: boolean;
    branches: { data: Branch[] };
    currencies: { data: Currency[] };
    warehouses: { data: Warehouse[] };
    vendors: { data: Vendor[] };
    locale: string;
    localizations?: { data: Organization[] };
  };
}
export interface Organization_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  organization_id: string;
  title: string;
  is_default_org: boolean;
  user_role?: string;
  time_zone: string;
  language_code: string;
  date_format: string;
  field_separator: string;
  fiscal_year_start_month: number;
  tax_group_enabled: boolean;
  industry_type: string;
  stage: Stage;
  full_name?: string;
  owner?: User_Plain;
  images?: Media[];
  logo?: Media;
  members?: User_Plain[];
  active?: boolean;
  has_branch?: boolean;
  branches: Branch_Plain[];
  currencies: Currency_Plain[];
  warehouses: Warehouse_Plain[];
  vendors: Vendor_Plain[];
  locale: string;
  localizations?: Organization[];
}

export interface Organization_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  organization_id: string;
  title: string;
  is_default_org: boolean;
  user_role?: string;
  time_zone: string;
  language_code: string;
  date_format: string;
  field_separator: string;
  fiscal_year_start_month: number;
  tax_group_enabled: boolean;
  industry_type: string;
  stage: Stage;
  full_name?: string;
  owner?: number;
  images?: number[];
  logo?: number;
  members?: number[];
  active?: boolean;
  has_branch?: boolean;
  branches: number[];
  currencies: number[];
  warehouses: number[];
  vendors: number[];
  locale: string;
  localizations?: Organization[];
}

export interface Organization_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  organization_id: string;
  title: string;
  is_default_org: boolean;
  user_role?: string;
  time_zone: string;
  language_code: string;
  date_format: string;
  field_separator: string;
  fiscal_year_start_month: number;
  tax_group_enabled: boolean;
  industry_type: string;
  stage: Stage;
  full_name?: string;
  owner?: AdminPanelRelationPropertyModification<User_Plain>;
  images?: AdminPanelRelationPropertyModification<Media>[];
  logo?: AdminPanelRelationPropertyModification<Media>;
  members?: AdminPanelRelationPropertyModification<User_Plain>;
  active?: boolean;
  has_branch?: boolean;
  branches: AdminPanelRelationPropertyModification<Branch_Plain>;
  currencies: AdminPanelRelationPropertyModification<Currency_Plain>;
  warehouses: AdminPanelRelationPropertyModification<Warehouse_Plain>;
  vendors: AdminPanelRelationPropertyModification<Vendor_Plain>;
  locale: string;
  localizations?: Organization[];
}
