// Interface automatically generated by schemas-to-ts

import { User } from '../../../../common/schemas-to-ts/User';
import { Organization } from '../../../organization/content-types/organization/organization';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { Address } from '../../../address/content-types/address/address';
import { User_Plain } from '../../../../common/schemas-to-ts/User';
import { Organization_Plain } from '../../../organization/content-types/organization/organization';
import { Address_Plain } from '../../../address/content-types/address/address';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Store {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    domain?: string;
    owner?: { data: User };
    organization?: { data: Organization };
    logo?: { data: Media };
    active?: boolean;
    is_open: boolean;
    address?: { data: Address };
    locale: string;
    localizations?: { data: Store[] };
  };
}
export interface Store_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  domain?: string;
  owner?: User_Plain;
  organization?: Organization_Plain;
  logo?: Media;
  active?: boolean;
  is_open: boolean;
  address?: Address_Plain;
  locale: string;
  localizations?: Store[];
}

export interface Store_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  domain?: string;
  owner?: number;
  organization?: number;
  logo?: number;
  active?: boolean;
  is_open: boolean;
  address?: number;
  locale: string;
  localizations?: Store[];
}

export interface Store_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  domain?: string;
  owner?: AdminPanelRelationPropertyModification<User_Plain>;
  organization?: AdminPanelRelationPropertyModification<Organization_Plain>;
  logo?: AdminPanelRelationPropertyModification<Media>;
  active?: boolean;
  is_open: boolean;
  address?: AdminPanelRelationPropertyModification<Address_Plain>;
  locale: string;
  localizations?: Store[];
}
