// Interface automatically generated by schemas-to-ts

export enum Status {
  Shipped = 'shipped',
  InTransit = 'in_transit',
  Delivered = 'delivered',
  Pending = 'pending',
  Cancelled = 'cancelled',}
export enum DiscountType {
  EntityLevel = 'entity_level',
  ItemLevel = 'item_level',}
export enum TemplateType {
  Standard = 'standard',
  Custom = 'custom',}

export interface Shipment {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    salesorder_id?: number;
    salesorder_number: string;
    shipment_id?: number;
    shipment_number: string;
    date?: Date;
    status?: Status;
    detailed_status?: string;
    status_message?: string;
    carrier?: string;
    service?: string;
    delivery_days?: number;
    delivery_guarantee?: boolean;
    reference_number?: string;
    customer_id?: number;
    customer_name?: string;
    contact_persons?: number;
    currency_id?: number;
    currency_code?: string;
    currency_symbol?: string;
    exchange_rate?: number;
    discount_amount?: number;
    discount?: string;
    is_discount_before_tax?: boolean;
    discount_type?: DiscountType;
    estimate_id?: number;
    delivery_method?: string;
    delivery_method_id?: number;
    tracking_number?: string;
    shipping_charge?: number;
    sub_total?: number;
    tax_total?: number;
    total?: number;
    price_precision?: number;
    is_emailed?: boolean;
    template_id?: number;
    template_name?: string;
    template_type?: TemplateType;
    notes?: string;
    created_time?: Date;
    last_modified_time?: Date;
    locale: string;
    localizations?: { data: Shipment[] };
  };
}
export interface Shipment_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  salesorder_id?: number;
  salesorder_number: string;
  shipment_id?: number;
  shipment_number: string;
  date?: Date;
  status?: Status;
  detailed_status?: string;
  status_message?: string;
  carrier?: string;
  service?: string;
  delivery_days?: number;
  delivery_guarantee?: boolean;
  reference_number?: string;
  customer_id?: number;
  customer_name?: string;
  contact_persons?: number;
  currency_id?: number;
  currency_code?: string;
  currency_symbol?: string;
  exchange_rate?: number;
  discount_amount?: number;
  discount?: string;
  is_discount_before_tax?: boolean;
  discount_type?: DiscountType;
  estimate_id?: number;
  delivery_method?: string;
  delivery_method_id?: number;
  tracking_number?: string;
  shipping_charge?: number;
  sub_total?: number;
  tax_total?: number;
  total?: number;
  price_precision?: number;
  is_emailed?: boolean;
  template_id?: number;
  template_name?: string;
  template_type?: TemplateType;
  notes?: string;
  created_time?: Date;
  last_modified_time?: Date;
  locale: string;
  localizations?: Shipment[];
}

export interface Shipment_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  salesorder_id?: number;
  salesorder_number: string;
  shipment_id?: number;
  shipment_number: string;
  date?: Date;
  status?: Status;
  detailed_status?: string;
  status_message?: string;
  carrier?: string;
  service?: string;
  delivery_days?: number;
  delivery_guarantee?: boolean;
  reference_number?: string;
  customer_id?: number;
  customer_name?: string;
  contact_persons?: number;
  currency_id?: number;
  currency_code?: string;
  currency_symbol?: string;
  exchange_rate?: number;
  discount_amount?: number;
  discount?: string;
  is_discount_before_tax?: boolean;
  discount_type?: DiscountType;
  estimate_id?: number;
  delivery_method?: string;
  delivery_method_id?: number;
  tracking_number?: string;
  shipping_charge?: number;
  sub_total?: number;
  tax_total?: number;
  total?: number;
  price_precision?: number;
  is_emailed?: boolean;
  template_id?: number;
  template_name?: string;
  template_type?: TemplateType;
  notes?: string;
  created_time?: Date;
  last_modified_time?: Date;
  locale: string;
  localizations?: Shipment[];
}

export interface Shipment_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  salesorder_id?: number;
  salesorder_number: string;
  shipment_id?: number;
  shipment_number: string;
  date?: Date;
  status?: Status;
  detailed_status?: string;
  status_message?: string;
  carrier?: string;
  service?: string;
  delivery_days?: number;
  delivery_guarantee?: boolean;
  reference_number?: string;
  customer_id?: number;
  customer_name?: string;
  contact_persons?: number;
  currency_id?: number;
  currency_code?: string;
  currency_symbol?: string;
  exchange_rate?: number;
  discount_amount?: number;
  discount?: string;
  is_discount_before_tax?: boolean;
  discount_type?: DiscountType;
  estimate_id?: number;
  delivery_method?: string;
  delivery_method_id?: number;
  tracking_number?: string;
  shipping_charge?: number;
  sub_total?: number;
  tax_total?: number;
  total?: number;
  price_precision?: number;
  is_emailed?: boolean;
  template_id?: number;
  template_name?: string;
  template_type?: TemplateType;
  notes?: string;
  created_time?: Date;
  last_modified_time?: Date;
  locale: string;
  localizations?: Shipment[];
}
