// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Store } from '../../../store/content-types/store/store';
import { User } from '../../../../common/schemas-to-ts/User';
import { AttributeGroup } from '../../../attribute-group/content-types/attribute-group/attribute-group';
import { Store_Plain } from '../../../store/content-types/store/store';
import { User_Plain } from '../../../../common/schemas-to-ts/User';
import { AttributeGroup_Plain } from '../../../attribute-group/content-types/attribute-group/attribute-group';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface AttributeFamily {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    meta?: any;
    active?: boolean;
    image?: { data: Media };
    store?: { data: Store };
    user?: { data: User };
    attribute_groups?: { data: AttributeGroup[] };
    code?: string;
    locale: string;
    localizations?: { data: AttributeFamily[] };
  };
}
export interface AttributeFamily_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  meta?: any;
  active?: boolean;
  image?: Media;
  store?: Store_Plain;
  user?: User_Plain;
  attribute_groups?: AttributeGroup_Plain[];
  code?: string;
  locale: string;
  localizations?: AttributeFamily[];
}

export interface AttributeFamily_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  meta?: any;
  active?: boolean;
  image?: number;
  store?: number;
  user?: number;
  attribute_groups?: number[];
  code?: string;
  locale: string;
  localizations?: AttributeFamily[];
}

export interface AttributeFamily_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  meta?: any;
  active?: boolean;
  image?: AdminPanelRelationPropertyModification<Media>;
  store?: AdminPanelRelationPropertyModification<Store_Plain>;
  user?: AdminPanelRelationPropertyModification<User_Plain>;
  attribute_groups?: AdminPanelRelationPropertyModification<AttributeGroup_Plain>;
  code?: string;
  locale: string;
  localizations?: AttributeFamily[];
}
