// Interface automatically generated by schemas-to-ts

export interface PaymentGateway {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    configured: boolean;
    additional_field: string;
    custom_fields?: any;
    gateway_name: string;
    locale: string;
    localizations?: { data: PaymentGateway[] };
  };
}
export interface PaymentGateway_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  configured: boolean;
  additional_field: string;
  custom_fields?: any;
  gateway_name: string;
  locale: string;
  localizations?: PaymentGateway[];
}

export interface PaymentGateway_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  configured: boolean;
  additional_field: string;
  custom_fields?: any;
  gateway_name: string;
  locale: string;
  localizations?: PaymentGateway[];
}

export interface PaymentGateway_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  configured: boolean;
  additional_field: string;
  custom_fields?: any;
  gateway_name: string;
  locale: string;
  localizations?: PaymentGateway[];
}
