// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Store } from '../../../store/content-types/store/store';
import { Store_Plain } from '../../../store/content-types/store/store';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Brand {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    full_name?: string;
    active?: boolean;
    logo?: { data: Media };
    images?: { data: Media[] };
    description?: string;
    store?: { data: Store };
    locale: string;
    localizations?: { data: Brand[] };
  };
}
export interface Brand_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  full_name?: string;
  active?: boolean;
  logo?: Media;
  images?: Media[];
  description?: string;
  store?: Store_Plain;
  locale: string;
  localizations?: Brand[];
}

export interface Brand_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  full_name?: string;
  active?: boolean;
  logo?: number;
  images?: number[];
  description?: string;
  store?: number;
  locale: string;
  localizations?: Brand[];
}

export interface Brand_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  full_name?: string;
  active?: boolean;
  logo?: AdminPanelRelationPropertyModification<Media>;
  images?: AdminPanelRelationPropertyModification<Media>[];
  description?: string;
  store?: AdminPanelRelationPropertyModification<Store_Plain>;
  locale: string;
  localizations?: Brand[];
}
