// Interface automatically generated by schemas-to-ts

export interface Cart {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    code: string;
    total_price: number;
    quantity: number;
    locale: string;
    localizations?: { data: Cart[] };
  };
}
export interface Cart_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  code: string;
  total_price: number;
  quantity: number;
  locale: string;
  localizations?: Cart[];
}

export interface Cart_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  code: string;
  total_price: number;
  quantity: number;
  locale: string;
  localizations?: Cart[];
}

export interface Cart_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  code: string;
  total_price: number;
  quantity: number;
  locale: string;
  localizations?: Cart[];
}
