// Interface automatically generated by schemas-to-ts

export interface Collection {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    slug: string;
    description: string;
    tax_id: number;
    is_selected: boolean;
    active: boolean;
    visibility: boolean;
    sort_by_options?: any;
    bread_crumbs?: any;
    specifications?: any;
    parent_id: string;
    items?: any;
    number_columns: number;
    order: number;
    locale: string;
    localizations?: { data: Collection[] };
  };
}
export interface Collection_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  slug: string;
  description: string;
  tax_id: number;
  is_selected: boolean;
  active: boolean;
  visibility: boolean;
  sort_by_options?: any;
  bread_crumbs?: any;
  specifications?: any;
  parent_id: string;
  items?: any;
  number_columns: number;
  order: number;
  locale: string;
  localizations?: Collection[];
}

export interface Collection_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  slug: string;
  description: string;
  tax_id: number;
  is_selected: boolean;
  active: boolean;
  visibility: boolean;
  sort_by_options?: any;
  bread_crumbs?: any;
  specifications?: any;
  parent_id: string;
  items?: any;
  number_columns: number;
  order: number;
  locale: string;
  localizations?: Collection[];
}

export interface Collection_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  slug: string;
  description: string;
  tax_id: number;
  is_selected: boolean;
  active: boolean;
  visibility: boolean;
  sort_by_options?: any;
  bread_crumbs?: any;
  specifications?: any;
  parent_id: string;
  items?: any;
  number_columns: number;
  order: number;
  locale: string;
  localizations?: Collection[];
}
