// Interface automatically generated by schemas-to-ts

import { AttributeFamily } from '../../../attribute-family/content-types/attribute-family/attribute-family';
import { Store } from '../../../store/content-types/store/store';
import { User } from '../../../../common/schemas-to-ts/User';
import { AttributeFamily_Plain } from '../../../attribute-family/content-types/attribute-family/attribute-family';
import { Store_Plain } from '../../../store/content-types/store/store';
import { User_Plain } from '../../../../common/schemas-to-ts/User';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface AttributeGroup {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    description?: string;
    attribute_families?: { data: AttributeFamily[] };
    store?: { data: Store };
    active?: boolean;
    users_permissions_user?: { data: User };
    title?: string;
    code?: string;
    locale: string;
    localizations?: { data: AttributeGroup[] };
  };
}
export interface AttributeGroup_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  description?: string;
  attribute_families?: AttributeFamily_Plain[];
  store?: Store_Plain;
  active?: boolean;
  users_permissions_user?: User_Plain;
  title?: string;
  code?: string;
  locale: string;
  localizations?: AttributeGroup[];
}

export interface AttributeGroup_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  description?: string;
  attribute_families?: number[];
  store?: number;
  active?: boolean;
  users_permissions_user?: number;
  title?: string;
  code?: string;
  locale: string;
  localizations?: AttributeGroup[];
}

export interface AttributeGroup_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  description?: string;
  attribute_families?: AdminPanelRelationPropertyModification<AttributeFamily_Plain>[];
  store?: AdminPanelRelationPropertyModification<Store_Plain>;
  active?: boolean;
  users_permissions_user?: AdminPanelRelationPropertyModification<User_Plain>;
  title?: string;
  code?: string;
  locale: string;
  localizations?: AttributeGroup[];
}
