// Interface automatically generated by schemas-to-ts

export interface CartItem {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    quantity: number;
    label_price: number;
    total_price: number;
    discount_amount: number;
    locale: string;
    localizations?: { data: CartItem[] };
  };
}
export interface CartItem_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  quantity: number;
  label_price: number;
  total_price: number;
  discount_amount: number;
  locale: string;
  localizations?: CartItem[];
}

export interface CartItem_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  quantity: number;
  label_price: number;
  total_price: number;
  discount_amount: number;
  locale: string;
  localizations?: CartItem[];
}

export interface CartItem_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  quantity: number;
  label_price: number;
  total_price: number;
  discount_amount: number;
  locale: string;
  localizations?: CartItem[];
}
