// Interface automatically generated by schemas-to-ts

export interface Attribute {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    code?: string;
    type?: string;
    validation?: string;
    is_required?: boolean;
    active?: boolean;
    is_unique?: boolean;
    is_filterable?: boolean;
    is_visible?: boolean;
  };
}
export interface Attribute_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  code?: string;
  type?: string;
  validation?: string;
  is_required?: boolean;
  active?: boolean;
  is_unique?: boolean;
  is_filterable?: boolean;
  is_visible?: boolean;
}

export interface Attribute_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  code?: string;
  type?: string;
  validation?: string;
  is_required?: boolean;
  active?: boolean;
  is_unique?: boolean;
  is_filterable?: boolean;
  is_visible?: boolean;
}

export interface Attribute_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  code?: string;
  type?: string;
  validation?: string;
  is_required?: boolean;
  active?: boolean;
  is_unique?: boolean;
  is_filterable?: boolean;
  is_visible?: boolean;
}
