name: remote ssh command

on:
  push:
    branches:
      - develop

jobs:

  build:
    name: develop
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          password: ${{ secrets.DEV_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: ${{ secret.COMMAND }}
