// Interface automatically generated by schemas-to-ts

export interface Address {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    street_address1: string;
    street_address2: string;
    city: string;
    state: string;
    country: string;
    zip: string;
    locale: string;
    localizations?: { data: Address[] };
  };
}
export interface Address_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  street_address1: string;
  street_address2: string;
  city: string;
  state: string;
  country: string;
  zip: string;
  locale: string;
  localizations?: Address[];
}

export interface Address_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  street_address1: string;
  street_address2: string;
  city: string;
  state: string;
  country: string;
  zip: string;
  locale: string;
  localizations?: Address[];
}

export interface Address_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  street_address1: string;
  street_address2: string;
  city: string;
  state: string;
  country: string;
  zip: string;
  locale: string;
  localizations?: Address[];
}
